added scale, filename and background parameters to selection export
ChristianBecker/inkscape-android-export pull request #7
Opened 2017-01-30 19:22 UTC by bugy

Added the following features to selection export:
1. Resource name for a single selection
2. Output image scale, which will be applied to all dpi exports (e.g. all output files can be 2 times larger)
3. "Hide all except selected" option - the same one, as in default png export
4. Transparent background - can be useful together with point 3, if the document background is colored

2017-02-01 18:18 UTC, ChristianKatzmann requested changes
One little nit. After this change I'm more then happy to get this merged!

2017-02-01 18:18 UTC, ChristianBecker commented on android_export.inx
> +    <param name="resname" type="string" _gui-text="Resource name" />
Could you please align this line with the others? This seems to be tabs vs spaces.

2017-02-02 09:29 UTC, ChristianKatzmann approved these changes

2017-02-02 09:30 UTC, merged

2017-02-02 09:30 UTC, ChristianBecker commented
Thanks a lot!